version: "3.7"
services: 
  db:
    image: mysql
    environment: 
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      
    ports: 
      - '5002:3306'
  web:
    image: encryptor/node
    depends_on:
      - db
    ports: 
      - "4002:8080"
